name: pr
on:
  pull_request:
    types: [ opened, synchronize, edited ]
    paths-ignore:
      - README.md
      - LICENSE
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
env:
  GITHUB_USER: ${{ secrets.GITHUB_ACTOR }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up Ruby from .ruby-version
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: build
        run: |
          ./gradlew --continue clean
          mkdir -p build/reports
          ./gradlew --continue build --stacktrace 2>build/reports/build-error-log.txt
      - name: lint and test
        if: success()
        run: ./gradlew --continue ktlintCheck lintDebug testDebug --stacktrace
      - name: 'Upload lint and test reports'
        uses: actions/upload-artifact@v4
        if: cancelled() != true
        with:
          name: reports
          path: |
            **/build/reports
            **/build/test-results
          retention-days: 7
      - name: Run Danger
        if: cancelled() != true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JOB_STATUS: ${{ job.status }}
        run: bundle exec danger --remove-previous-comments --fail-on-errors=true
