name: pr

on:
  pull_request:
    types: [opened, synchronize, edited]
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up Ruby from .ruby-version
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: lint and test
      run: ./gradlew --continue clean ktlintCheck lintDebug testDebug --stacktrace
    - name: 'Upload lint and test reports'
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          **/build/reports
          **/build/test-results
        retention-days: 7
    - name: Run Danger
      if: cancelled() != true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JOB_STATUS: ${{ job.status }}
      run: |
        bundle exec danger --remove-previous-comments --fail-on-errors=true
